spring:
  datasource:
    url: jdbc:h2:file:./data/marketdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: false
  sql:
    init:
      mode: never
  h2:
    console:
      enabled: true
log:
  monitor:
    directory: ${user.home}/Saved Games/Frontier Developments/Elite Dangerous
logging:
  level:
    org.springframework.context: DEBUG
    root: INFO